try:
    from ._bootstrap import PROJECT_ROOT  # noqa: F401
except ImportError:
    from _bootstrap import PROJECT_ROOT  # noqa: F401

from pathlib import Path
import argparse
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import paths
from classifier.config import CLASS_DICT


METHODS = [
    ('pca', 'PCA'),
    ('tsne', 't-SNE'),
    ('umap', 'UMAP'),
]

DENV_COLORS = {
    'DENV-1': '#66c2a5',
    'DENV-2': '#fc8d62',
    'DENV-3': '#8da0cb',
    'DENV-4': '#e78ac3',
}

OUTPUT_DIR_NAME = 'output-per-fold'
ACROSS_SPLITS_OUTPUT_DIR_NAME = 'output-across-splits'
DATASET_OUTPUT_DIR_NAME = 'output-aggregate-dataset'

EXPERIMENT_ORDER = [
    'ohe_continent_e100',
    'ohe_timebin_e100',
    'ohe_cdhit_e100',
]

EXPERIMENT_TITLES = {
    'ohe_cdhit_e100': 'CD-HIT',
    'ohe_continent_e100': 'Geographical',
    'ohe_timebin_e100': 'Temporal',
    'all_experiments': 'Overall',
}

MODEL_TITLES = {
    'denformer_first': 'DENFormer-first',
    'denformer_mean': 'DENFormer-mean',
    'denformer_max': 'DENFormer-max',
}

TEMPORAL_FOLD_TITLES = {
    '2006': '< 2006',
    '-2006': '< 2006',
    '<2006': '< 2006',
    '<_2006': '< 2006',
    '<-2006': '< 2006',
    'pre_2006': '< 2006',
    'pre-2006': '< 2006',
    'before_2006': '< 2006',
    'before-2006': '< 2006',
    'lt_2006': '< 2006',
    'lt-2006': '< 2006',
    '2006-2010': '2006-2010',
    '2006_2010': '2006-2010',
    '2011-2015': '2011-2015',
    '2011_2015': '2011-2015',
    '2016-2020': '2016-2020',
    '2016_2020': '2016-2020',
    '2021-2025': '2021-2025',
    '2021_2025': '2021-2025',
}

TEMPORAL_FOLD_ORDER = ['< 2006', '2006-2010', '2011-2015', '2016-2020', '2021-2025']
CONTINENT_FOLD_ORDER = ['Africa', 'Asia', 'Europe', 'Oceania', 'North America', 'South America']
COMBINED_GEO_FOLD_LABEL = 'Europe + Oceania'
COMBINED_GEO_FOLDS = {'Europe', 'Oceania'}

# Larger defaults for paper-readable multi-panel figures.
TITLE_FONTSIZE = 20
PANEL_TITLE_FONTSIZE = 17
AXIS_LABEL_FONTSIZE = 15
TICK_LABEL_FONTSIZE = 13
LEGEND_FONTSIZE = 15
LEGEND_MARKER_SIZE = 12
SCATTER_SIZE = 16
SCATTER_ALPHA = 0.75


METHOD_AXIS_PREFIX = {
    'PCA': 'PCA',
    't-SNE': 't-SNE',
    'UMAP': 'UMAP',
}


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            'Aggregate fold-level XAI embedding projection plots into horizontal '
            'per-fold panels. The script reads projection CSVs generated by '
            'classifier.workflow.xai_embeddings and writes panels under output-per-fold.'
        )
    )
    parser.add_argument(
        '--root',
        default=None,
        help=(
            'Root directory containing embedding plot outputs. Default: '
            '<logs_dir>/aggregate_xai/embeddings_xai.'
        ),
    )
    parser.add_argument(
        '--xai-plot-dir',
        default=None,
        help=(
            'Aggregate one specific directory, e.g. '
            '.../aggregate_xai/embeddings_xai/denformer_mean/ohe_continent_e100.'
        ),
    )
    parser.add_argument('--subset', default='test', help='Projection subset to aggregate. Default: test.')
    parser.add_argument('--model-filter', default='denformer', help='Only aggregate directories whose path contains this text. Default: denformer.')
    parser.add_argument('--dpi', type=int, default=300, help='Output image DPI. Default: 300.')
    parser.add_argument('--max-cols', type=int, default=None, help='Optional maximum number of fold columns per figure.')
    parser.add_argument('--overwrite', action='store_true', help='Overwrite existing aggregate PNG files.')
    parser.add_argument(
        '--skip-per-fold',
        action='store_true',
        help='Skip fold-level panels and generate only across-split panels.',
    )
    parser.add_argument(
        '--skip-across-splits',
        action='store_true',
        help='Skip model-level panels comparing split strategies.',
    )
    parser.add_argument(
        '--skip-across-split-fold-grid',
        action='store_true',
        help=(
            'Skip model-level grid panels where rows are split strategies and '
            'columns are folds. By default these are generated under output-across-splits.'
        ),
    )
    return parser.parse_args()


def _default_root():
    return Path(paths.logs_dir) / 'aggregate_xai' / 'embeddings_xai'


def _raw_fold_token(split_dir):
    name = Path(split_dir).name
    if name.startswith('split_'):
        name = name[len('split_'):]
    return name


def _fold_sort_key(path):
    path = Path(path)
    token = _raw_fold_token(path)
    display = _display_fold_name(path)
    exp_name = path.parent.name

    if exp_name == 'ohe_timebin_e100':
        try:
            return (0, TEMPORAL_FOLD_ORDER.index(display), token)
        except ValueError:
            return (0, len(TEMPORAL_FOLD_ORDER), token)

    if exp_name == 'ohe_continent_e100':
        try:
            return (0, CONTINENT_FOLD_ORDER.index(display), token)
        except ValueError:
            return (0, len(CONTINENT_FOLD_ORDER), token)

    match = re.search(r'(\d+)', token)
    if match:
        return (0, int(match.group(1)), token)
    return (1, token)




def _display_experiment_name(xai_plot_dir):
    name = Path(xai_plot_dir).name
    if name in EXPERIMENT_TITLES:
        return EXPERIMENT_TITLES[name]

    # Fallback for unexpected folders: still avoid raw code-like names when possible.
    clean = name
    clean = re.sub(r'^ohe_', '', clean)
    clean = re.sub(r'_e\d+$', '', clean)
    clean = clean.replace('cdhit', 'CD-HIT')
    clean = clean.replace('timebin', 'Temporal')
    clean = clean.replace('continent', 'Geographical')
    clean = clean.replace('_', ' ')
    return clean.title().replace('Cd-Hit', 'CD-HIT')


def _experiment_sort_key(path):
    name = Path(path).name
    if name in EXPERIMENT_ORDER:
        return (0, EXPERIMENT_ORDER.index(name), name)
    return (1, name)


def _is_experiment_dir(path):
    path = Path(path)
    return path.name in EXPERIMENT_TITLES and any(path.glob('split_*'))


def _is_model_dir(path):
    path = Path(path)
    return path.is_dir() and any((path / exp).is_dir() for exp in EXPERIMENT_ORDER)


def _find_model_dirs(root, model_filter):
    root = Path(root)
    if not root.exists():
        print(f'[WARN] Root does not exist: {root}')
        return []

    model_dirs = []
    for model_dir in root.glob('*'):
        if not model_dir.is_dir():
            continue
        if model_filter and model_filter not in model_dir.name:
            continue
        if _is_model_dir(model_dir):
            model_dirs.append(model_dir)
    return sorted(model_dirs)


def _find_experiment_dirs_for_model(model_dir):
    model_dir = Path(model_dir)
    experiments = []
    for exp_dir in model_dir.iterdir() if model_dir.exists() else []:
        if not exp_dir.is_dir():
            continue
        if exp_dir.name == ACROSS_SPLITS_OUTPUT_DIR_NAME:
            continue
        if exp_dir.name.startswith('output-'):
            continue
        if _find_dataset_projection_path(exp_dir, METHODS[0][0], 'test') or any(exp_dir.glob('split_*')):
            experiments.append(exp_dir)
    return sorted(experiments, key=_experiment_sort_key)


def _display_fold_name(split_dir):
    split_dir = Path(split_dir)
    token = _raw_fold_token(split_dir)

    if split_dir.parent.name == 'ohe_timebin_e100':
        normalized = token.strip()
        normalized_hyphen = normalized.replace('_', '-')
        normalized_lower = normalized_hyphen.lower()

        if normalized in TEMPORAL_FOLD_TITLES:
            return TEMPORAL_FOLD_TITLES[normalized]
        if normalized_hyphen in TEMPORAL_FOLD_TITLES:
            return TEMPORAL_FOLD_TITLES[normalized_hyphen]
        if normalized_lower in TEMPORAL_FOLD_TITLES:
            return TEMPORAL_FOLD_TITLES[normalized_lower]

        # Robust fallback for folders named split_-2006, split_<2006, split_before2006, etc.
        compact = re.sub(r'[^0-9a-zA-Z<]+', '', normalized_lower)
        if compact in {'2006', '<2006', 'lt2006', 'pre2006', 'before2006'} or normalized_lower.startswith('-2006'):
            return '< 2006'

        return normalized_hyphen

    if split_dir.parent.name == 'ohe_cdhit_e100':
        match = re.search(r'(\d+)', token)
        if match:
            return f'Fold {int(match.group(1))}'
        return token.replace('_', ' ').title()

    return token.replace('_', ' ')


def _display_model_name(model_dir):
    name = Path(model_dir).name
    if name in MODEL_TITLES:
        return MODEL_TITLES[name]
    return name.replace('_', ' ')


def _method_csv_path(split_dir, method, subset):
    return Path(split_dir) / f'{method}_embeddings_{subset}.csv'


def _find_dataset_projection_path(experiment_dir, method, subset):
    experiment_dir = Path(experiment_dir)
    aggregate_dir = experiment_dir / DATASET_OUTPUT_DIR_NAME

    candidates = [
        aggregate_dir / f'{method}_embeddings_{subset}.csv',
        aggregate_dir / f'{method}_embeddings_dataset_{subset}.csv',
        aggregate_dir / f'{method}_embeddings_{subset}_dataset.csv',
        experiment_dir / f'{method}_embeddings_{subset}.csv',
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate

    for base in [aggregate_dir, experiment_dir]:
        if not base.exists():
            continue
        matches = sorted(base.glob(f'{method}_embeddings*{subset}*.csv'))
        matches = [m for m in matches if 'summary' not in m.name.lower()]
        if matches:
            return matches[0]
    return None


def _find_candidate_dirs(root, model_filter):
    root = Path(root)
    if not root.exists():
        print(f'[WARN] Root does not exist: {root}')
        return []

    candidates = []
    for split_dir in root.rglob('split_*'):
        if not split_dir.is_dir():
            continue
        parent = split_dir.parent
        if model_filter and model_filter not in str(parent):
            continue
        if any(_method_csv_path(split_dir, method, 'test').exists() for method, _ in METHODS):
            candidates.append(parent)

    unique = sorted(set(candidates))
    return unique


def _find_split_dirs(xai_plot_dir, subset):
    split_dirs = []
    for split_dir in Path(xai_plot_dir).glob('split_*'):
        if not split_dir.is_dir():
            continue
        if any(_method_csv_path(split_dir, method, subset).exists() for method, _ in METHODS):
            split_dirs.append(split_dir)
    return sorted(split_dirs, key=_fold_sort_key)


def _read_projection(csv_path):
    df = pd.read_csv(csv_path)
    required = {'x', 'y', 'label'}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f'Missing columns {sorted(missing)} in {csv_path}')
    df = df.copy()
    df['label'] = df['label'].astype(int)
    return df


def _label_to_name(label):
    return CLASS_DICT.get(int(label), f'Class {int(label)}')


def _format_axis_labels(method_label):
    prefix = METHOD_AXIS_PREFIX.get(method_label, method_label)
    return f'{prefix}-1', f'{prefix}-2'


def _style_axis(ax):
    ax.tick_params(axis='both', which='major', labelsize=TICK_LABEL_FONTSIZE)
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_linewidth(1.0)


def _plot_projection_on_axis(ax, df, method_label, show_xlabel=True, show_ylabel=True, title=None):
    for label in sorted(df['label'].unique()):
        class_name = _label_to_name(label)
        sub = df[df['label'] == label]
        ax.scatter(
            sub['x'],
            sub['y'],
            s=SCATTER_SIZE,
            alpha=SCATTER_ALPHA,
            linewidths=0,
            color=DENV_COLORS.get(class_name),
            label=class_name,
        )

    x_label, y_label = _format_axis_labels(method_label)
    ax.set_xlabel(x_label if show_xlabel else '', fontsize=AXIS_LABEL_FONTSIZE, labelpad=6)
    ax.set_ylabel(y_label if show_ylabel else '', fontsize=AXIS_LABEL_FONTSIZE, labelpad=8)
    if title:
        ax.set_title(title, fontsize=PANEL_TITLE_FONTSIZE, pad=10)
    _style_axis(ax)


def _build_fold_plot_entries(exp_dir, method, subset, combine_geographical_small_folds=False):
    entries = []
    pending_combined = []

    for split_dir, csv_path in _available_fold_csvs_for_experiment(exp_dir, method, subset):
        fold_label = _display_fold_name(split_dir)

        if (
            combine_geographical_small_folds
            and Path(exp_dir).name == 'ohe_continent_e100'
            and fold_label in COMBINED_GEO_FOLDS
        ):
            pending_combined.append((fold_label, split_dir, csv_path))
            continue

        if pending_combined and fold_label == 'North America':
            pending_combined = sorted(
                pending_combined,
                key=lambda item: CONTINENT_FOLD_ORDER.index(item[0])
                if item[0] in CONTINENT_FOLD_ORDER else 999,
            )
            entries.append({
                'kind': 'combined',
                'label': COMBINED_GEO_FOLD_LABEL,
                'parts': pending_combined,
            })
            pending_combined = []

        entries.append({
            'kind': 'single',
            'label': fold_label,
            'split_dir': split_dir,
            'csv_path': csv_path,
        })

    if pending_combined:
        pending_combined = sorted(
            pending_combined,
            key=lambda item: CONTINENT_FOLD_ORDER.index(item[0])
            if item[0] in CONTINENT_FOLD_ORDER else 999,
        )
        entries.append({
            'kind': 'combined',
            'label': COMBINED_GEO_FOLD_LABEL,
            'parts': pending_combined,
        })

    return entries


def _scale_to_unit(values, pad=0.06):
    values = np.asarray(values, dtype=float)
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return np.full_like(values, 0.5, dtype=float)
    vmin = float(np.min(finite))
    vmax = float(np.max(finite))
    if np.isclose(vmin, vmax):
        return np.full_like(values, 0.5, dtype=float)
    scaled = (values - vmin) / (vmax - vmin)
    return pad + scaled * (1.0 - 2.0 * pad)


def _plot_combined_projection_on_axis(ax, entry, method_label, show_xlabel=True, show_ylabel=True, title=None):
    """Render Europe and Oceania in one regular square axis.

    The two low-sample geographical folds are not drawn as nested subplots.
    Their coordinates are normalized separately and placed in the left/right
    half of the same axis, separated by a vertical bar. This keeps the panel
    visually comparable in size with the other fold panels while avoiding two
    tiny boxed insets.
    """
    x_label, y_label = _format_axis_labels(method_label)

    display_title = entry['label'] if title is None else title
    if display_title:
        ax.set_title(display_title, fontsize=PANEL_TITLE_FONTSIZE, pad=10)
    ax.set_xlabel(x_label if show_xlabel else '', fontsize=AXIS_LABEL_FONTSIZE, labelpad=6)
    ax.set_ylabel(y_label if show_ylabel else '', fontsize=AXIS_LABEL_FONTSIZE, labelpad=8)

    parts = sorted(
        entry['parts'],
        key=lambda item: CONTINENT_FOLD_ORDER.index(item[0])
        if item[0] in CONTINENT_FOLD_ORDER else 999,
    )[:2]

    # Use a common visual canvas: left half for Europe, right half for Oceania.
    # Each half uses its own min-max scaling because the goal of this combined
    # panel is readability of low-sample folds, not coordinate comparability.
    half_specs = {
        0: {'x0': 0.00, 'x1': 0.94, 'title_x': 0.47},
        1: {'x0': 1.06, 'x1': 2.00, 'title_x': 1.53},
    }

    for idx, (part_label, _split_dir, csv_path) in enumerate(parts):
        spec = half_specs[idx]
        df = _read_projection(csv_path)
        x_unit = _scale_to_unit(df['x'].to_numpy())
        y_unit = _scale_to_unit(df['y'].to_numpy())
        x_plot = spec['x0'] + x_unit * (spec['x1'] - spec['x0'])
        y_plot = y_unit

        for label in sorted(df['label'].unique()):
            class_name = _label_to_name(label)
            mask = df['label'].to_numpy() == label
            ax.scatter(
                x_plot[mask],
                y_plot[mask],
                s=SCATTER_SIZE,
                alpha=SCATTER_ALPHA,
                linewidths=0,
                color=DENV_COLORS.get(class_name),
                label=class_name,
            )

        ax.text(
            spec['title_x'],
            1.035,
            part_label,
            ha='center',
            va='bottom',
            fontsize=max(PANEL_TITLE_FONTSIZE - 2, 11),
            transform=ax.transData,
            clip_on=False,
        )

    ax.axvline(1.0, color='0.25', lw=1.2)
    ax.set_xlim(0.0, 2.0)
    ax.set_ylim(0.0, 1.0)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
    ax.grid(False)
    ax.set_box_aspect(1)
    for spine in ax.spines.values():
        spine.set_linewidth(1.0)

def _plot_fold_entry_on_axis(ax, entry, method_label, show_xlabel=True, show_ylabel=True, title=None):
    if entry['kind'] == 'combined':
        _plot_combined_projection_on_axis(
            ax,
            entry,
            method_label,
            show_xlabel=show_xlabel,
            show_ylabel=show_ylabel,
            title=title,
        )
        return

    df = _read_projection(entry['csv_path'])
    _plot_projection_on_axis(
        ax,
        df,
        method_label,
        show_xlabel=show_xlabel,
        show_ylabel=show_ylabel,
        title=title if title is not None else entry['label'],
    )


def _legend_handles():
    handles = []
    for label in [CLASS_DICT[k] for k in sorted(CLASS_DICT.keys())]:
        handles.append(
            plt.Line2D(
                [0],
                [0],
                marker='o',
                linestyle='',
                markersize=LEGEND_MARKER_SIZE,
                markerfacecolor=DENV_COLORS.get(label),
                markeredgecolor=DENV_COLORS.get(label),
                label=label,
            )
        )
    return handles


def _add_legend(fig):
    # Keep the legend close to the last column and inside the saved canvas.
    return fig.legend(
        handles=_legend_handles(),
        loc='center right',
        bbox_to_anchor=(0.992, 0.5),
        frameon=True,
        fontsize=LEGEND_FONTSIZE,
        borderaxespad=0.2,
        handletextpad=0.6,
        labelspacing=0.5,
    )


def _add_legend_in_axis(ax):
    ax.axis('off')
    return ax.legend(
        handles=_legend_handles(),
        loc='center',
        frameon=True,
        fontsize=LEGEND_FONTSIZE,
        borderaxespad=0.2,
        handletextpad=0.6,
        labelspacing=0.55,
    )


def _chunked(values, max_cols):
    if max_cols is None or max_cols <= 0 or len(values) <= max_cols:
        return [values]
    return [values[i:i + max_cols] for i in range(0, len(values), max_cols)]




def _lcm(values):
    values = [int(v) for v in values if int(v) > 0]
    if not values:
        return 1
    out = values[0]
    for value in values[1:]:
        out = out * value // np.gcd(out, value)
    return int(out)


def _save_method_panel(xai_plot_dir, split_dirs, method, method_label, subset, output_dir, dpi, overwrite, suffix=''):
    available = []
    for split_dir in split_dirs:
        csv_path = _method_csv_path(split_dir, method, subset)
        if csv_path.exists():
            available.append((split_dir, csv_path))

    if not available:
        print(f'[WARN] No {method_label} CSVs found for subset={subset} in {xai_plot_dir}')
        return []

    out_name = f'{method}_embeddings_{subset}_per_fold{suffix}.png'
    out_path = output_dir / out_name
    if out_path.exists() and not overwrite:
        print(f'[SKIP] Existing file: {out_path}')
        return [out_path]

    n_cols = len(available)
    fig_width = max(5.8 * n_cols + 1.4, 7.5)
    fig_height = 5.8
    fig, axes = plt.subplots(1, n_cols, figsize=(fig_width, fig_height), squeeze=False)
    axes = axes[0]

    for col, (split_dir, csv_path) in enumerate(available):
        df = _read_projection(csv_path)
        fold_label = _display_fold_name(split_dir)
        _plot_projection_on_axis(
            axes[col],
            df,
            method_label,
            show_xlabel=True,
            show_ylabel=(col == 0),
            title=fold_label,
        )

    _add_legend(fig)
    fig.suptitle(
        f'{method_label} embeddings across folds - {_display_experiment_name(xai_plot_dir)}',
        fontsize=TITLE_FONTSIZE,
        y=0.985,
    )
    fig.subplots_adjust(left=0.055, right=0.91, bottom=0.15, top=0.84, wspace=0.22)
    fig.savefig(out_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f'[OK] Saved {out_path}')
    return [out_path]


def _save_full_panel(xai_plot_dir, split_dirs, subset, output_dir, dpi, overwrite, suffix=''):
    panel_entries = []
    for split_dir in split_dirs:
        fold_entries = []
        for method, method_label in METHODS:
            csv_path = _method_csv_path(split_dir, method, subset)
            fold_entries.append((method, method_label, csv_path if csv_path.exists() else None))
        if any(csv_path is not None for _, _, csv_path in fold_entries):
            panel_entries.append((split_dir, fold_entries))

    if not panel_entries:
        print(f'[WARN] No projection CSVs found for full panel in {xai_plot_dir}')
        return []

    out_name = f'full_embeddings_{subset}_per_fold{suffix}.png'
    out_path = output_dir / out_name
    if out_path.exists() and not overwrite:
        print(f'[SKIP] Existing file: {out_path}')
        return [out_path]

    n_rows = len(METHODS)
    n_cols = len(panel_entries)
    fig_width = max(5.2 * n_cols + 1.4, 8.5)
    fig_height = 4.9 * n_rows
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(fig_width, fig_height), squeeze=False)

    for col, (split_dir, fold_entries) in enumerate(panel_entries):
        fold_label = _display_fold_name(split_dir)
        for row, (method, method_label, csv_path) in enumerate(fold_entries):
            ax = axes[row, col]
            if csv_path is None:
                ax.axis('off')
                if row == 0:
                    ax.set_title(f'{fold_label}\nmissing', fontsize=PANEL_TITLE_FONTSIZE, pad=10)
                continue

            df = _read_projection(csv_path)
            _plot_projection_on_axis(
                ax,
                df,
                method_label,
                show_xlabel=(row == n_rows - 1),
                show_ylabel=(col == 0),
                title=fold_label if row == 0 else None,
            )

    _add_legend(fig)
    fig.suptitle(
        f'Embedding projections across folds - {_display_experiment_name(xai_plot_dir)}',
        fontsize=TITLE_FONTSIZE,
        y=0.992,
    )
    # Larger left margin prevents ylabel/tick overlap; no extra rotated row labels are drawn.
    fig.subplots_adjust(left=0.06, right=0.91, bottom=0.07, top=0.91, wspace=0.24, hspace=0.28)
    fig.savefig(out_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f'[OK] Saved {out_path}')
    return [out_path]



def _save_across_splits_method_panel(model_dir, experiment_dirs, method, method_label, subset, output_dir, dpi, overwrite):
    available = []
    for exp_dir in experiment_dirs:
        csv_path = _find_dataset_projection_path(exp_dir, method, subset)
        if csv_path is not None and csv_path.exists():
            available.append((exp_dir, csv_path))

    if not available:
        print(f'[WARN] No dataset-level {method_label} CSVs found in {model_dir}')
        return []

    out_path = output_dir / f'{method}_embeddings_{subset}_across_split_strategies.png'
    if out_path.exists() and not overwrite:
        print(f'[SKIP] Existing file: {out_path}')
        return [out_path]

    n_cols = len(available)
    fig_width = max(5.9 * n_cols + 1.3, 8.0)
    fig_height = 5.8
    fig, axes = plt.subplots(1, n_cols, figsize=(fig_width, fig_height), squeeze=False)
    axes = axes[0]

    for col, (exp_dir, csv_path) in enumerate(available):
        df = _read_projection(csv_path)
        _plot_projection_on_axis(
            axes[col],
            df,
            method_label,
            show_xlabel=True,
            show_ylabel=(col == 0),
            title=_display_experiment_name(exp_dir),
        )

    _add_legend(fig)
    model_label = _display_model_name(model_dir)
    fig.suptitle(
        f'{method_label} embeddings across split strategies - {model_label}',
        fontsize=TITLE_FONTSIZE,
        y=0.985,
    )
    fig.subplots_adjust(left=0.055, right=0.90, bottom=0.15, top=0.84, wspace=0.24)
    fig.savefig(out_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f'[OK] Saved {out_path}')
    return [out_path]




def _available_fold_csvs_for_experiment(exp_dir, method, subset):
    entries = []
    for split_dir in _find_split_dirs(exp_dir, subset):
        csv_path = _method_csv_path(split_dir, method, subset)
        if csv_path.exists():
            entries.append((split_dir, csv_path))
    return entries


def _save_across_splits_fold_grid_method_panel(model_dir, experiment_dirs, method, method_label, subset, output_dir, dpi, overwrite):
    """Save one grid per reduction method: rows are split strategies, columns are folds.

    Uses a fixed six-column layout so panels remain square/readable.
    Rows with five folds leave the last column empty; the legend is placed in
    this bottom-right empty space rather than outside the figure.
    """
    row_entries = []
    for exp_dir in experiment_dirs:
        fold_entries = _build_fold_plot_entries(
            exp_dir,
            method,
            subset,
            combine_geographical_small_folds=False,
        )
        if fold_entries:
            row_entries.append((exp_dir, fold_entries))

    if not row_entries:
        print(f'[WARN] No fold-level {method_label} CSVs found for across-split grid in {model_dir}')
        return []

    out_path = output_dir / f'{method}_embeddings_{subset}_fold_grid_across_split_strategies.png'
    if out_path.exists() and not overwrite:
        print(f'[SKIP] Existing file: {out_path}')
        return [out_path]

    n_rows = len(row_entries)
    max_cols = max(6, max(len(fold_entries) for _, fold_entries in row_entries))

    panel_size = 3.85
    fig_width = panel_size * max_cols + 0.95
    fig_height = panel_size * n_rows + 0.65
    fig, axes = plt.subplots(n_rows, max_cols, figsize=(fig_width, fig_height), squeeze=False)

    legend_ax = None
    for row, (exp_dir, fold_entries) in enumerate(row_entries):
        exp_label = _display_experiment_name(exp_dir)
        for col in range(max_cols):
            ax = axes[row, col]
            if col >= len(fold_entries):
                ax.axis('off')
                # Prefer the empty bottom-right cell, which exists for the
                # temporal/CD-HIT rows, for a compact internal legend.
                if row == n_rows - 1 and col == max_cols - 1:
                    legend_ax = ax
                continue

            entry = fold_entries[col]
            _plot_fold_entry_on_axis(
                ax,
                entry,
                method_label,
                show_xlabel=(row == n_rows - 1),
                show_ylabel=(col == 0),
            )

            if col == 0:
                ax.annotate(
                    exp_label,
                    xy=(-0.42, 0.5),
                    xycoords='axes fraction',
                    rotation=90,
                    ha='center',
                    va='center',
                    fontsize=PANEL_TITLE_FONTSIZE,
                    fontweight='bold',
                )

    if legend_ax is None:
        _add_legend(fig)
        right = 0.905
    else:
        _add_legend_in_axis(legend_ax)
        right = 0.990

    model_label = _display_model_name(model_dir)
    fig.suptitle(model_label, fontsize=TITLE_FONTSIZE, y=0.995)
    fig.subplots_adjust(left=0.075, right=right, bottom=0.070, top=0.935, wspace=0.28, hspace=0.42)
    fig.savefig(out_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f'[OK] Saved {out_path}')
    return [out_path]

def _save_across_splits_full_fold_grid(model_dir, experiment_dirs, subset, output_dir, dpi, overwrite):
    """Save a larger grid with one block per split strategy and rows for PCA/t-SNE/UMAP.

    Uses a fixed six-column layout to keep panels square and consistent with
    the single-method across-split grids.
    """
    exp_entries = []
    for exp_dir in experiment_dirs:
        method_entries = []
        for method, method_label in METHODS:
            entries = _build_fold_plot_entries(
                exp_dir,
                method,
                subset,
                combine_geographical_small_folds=False,
            )
            method_entries.append((method, method_label, entries))
        if any(entries for _, _, entries in method_entries):
            exp_entries.append((exp_dir, method_entries))

    if not exp_entries:
        print(f'[WARN] No fold-level projection CSVs found for full across-split grid in {model_dir}')
        return []

    out_path = output_dir / f'full_embeddings_{subset}_fold_grid_across_split_strategies.png'
    if out_path.exists() and not overwrite:
        print(f'[SKIP] Existing file: {out_path}')
        return [out_path]

    n_method_rows = len(METHODS)
    n_exp = len(exp_entries)
    n_rows = n_exp * n_method_rows
    max_cols = 6

    panel_size = 3.55
    fig_width = panel_size * max_cols + 0.95
    fig_height = panel_size * n_rows + 0.8
    fig, axes = plt.subplots(n_rows, max_cols, figsize=(fig_width, fig_height), squeeze=False)

    legend_ax = None
    for exp_idx, (exp_dir, method_entries) in enumerate(exp_entries):
        exp_label = _display_experiment_name(exp_dir)
        for method_idx, (_method, method_label, fold_entries) in enumerate(method_entries):
            row = exp_idx * n_method_rows + method_idx
            for col in range(max_cols):
                ax = axes[row, col]
                if col >= len(fold_entries):
                    ax.axis('off')
                    if row == n_rows - 1 and col == max_cols - 1:
                        legend_ax = ax
                    continue

                entry = fold_entries[col]
                _plot_fold_entry_on_axis(
                    ax,
                    entry,
                    method_label,
                    show_xlabel=(row == n_rows - 1),
                    show_ylabel=(col == 0),
                    title=entry['label'] if method_idx == 0 else '',
                )

                if col == 0:
                    label = f'{exp_label}\n{method_label}' if method_idx == 0 else method_label
                    ax.annotate(
                        label,
                        xy=(-0.42, 0.5),
                        xycoords='axes fraction',
                        rotation=90,
                        ha='center',
                        va='center',
                        fontsize=PANEL_TITLE_FONTSIZE,
                        fontweight='bold' if method_idx == 0 else 'normal',
                    )

    if legend_ax is None:
        _add_legend(fig)
        right = 0.905
    else:
        _add_legend_in_axis(legend_ax)
        right = 0.990

    model_label = _display_model_name(model_dir)
    fig.suptitle(model_label, fontsize=TITLE_FONTSIZE, y=0.996)
    fig.subplots_adjust(left=0.075, right=right, bottom=0.045, top=0.965, wspace=0.28, hspace=0.38)
    fig.savefig(out_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f'[OK] Saved {out_path}')
    return [out_path]

def aggregate_across_splits_for_model(model_dir, subset, dpi, overwrite, make_fold_grid=True):
    model_dir = Path(model_dir)
    experiment_dirs = [
        model_dir / exp_name
        for exp_name in EXPERIMENT_ORDER
        if (model_dir / exp_name).is_dir()
    ]

    # Include any unexpected experiment folders after the canonical order.
    known = {p.resolve() for p in experiment_dirs}
    for exp_dir in _find_experiment_dirs_for_model(model_dir):
        if exp_dir.resolve() not in known:
            experiment_dirs.append(exp_dir)

    if not experiment_dirs:
        print(f'[WARN] No split-strategy directories found in {model_dir}')
        return []

    output_dir = model_dir / ACROSS_SPLITS_OUTPUT_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)

    saved = []
    for method, method_label in METHODS:
        saved.extend(
            _save_across_splits_method_panel(
                model_dir=model_dir,
                experiment_dirs=experiment_dirs,
                method=method,
                method_label=method_label,
                subset=subset,
                output_dir=output_dir,
                dpi=dpi,
                overwrite=overwrite,
            )
        )

    if make_fold_grid:
        for method, method_label in METHODS:
            saved.extend(
                _save_across_splits_fold_grid_method_panel(
                    model_dir=model_dir,
                    experiment_dirs=experiment_dirs,
                    method=method,
                    method_label=method_label,
                    subset=subset,
                    output_dir=output_dir,
                    dpi=dpi,
                    overwrite=overwrite,
                )
            )
        saved.extend(
            _save_across_splits_full_fold_grid(
                model_dir=model_dir,
                experiment_dirs=experiment_dirs,
                subset=subset,
                output_dir=output_dir,
                dpi=dpi,
                overwrite=overwrite,
            )
        )

    summary_path = output_dir / f'across_split_embedding_plot_summary_{subset}.csv'
    rows = []
    for exp_dir in experiment_dirs:
        row = {
            'experiment_dir': str(exp_dir),
            'split_strategy': _display_experiment_name(exp_dir),
        }
        fold_dirs = _find_split_dirs(exp_dir, subset)
        row['n_folds'] = len(fold_dirs)
        row['folds'] = ';'.join(_display_fold_name(split_dir) for split_dir in fold_dirs)
        for method, _ in METHODS:
            csv_path = _find_dataset_projection_path(exp_dir, method, subset)
            row[f'{method}_csv'] = str(csv_path) if csv_path is not None else ''
            row[f'{method}_exists'] = bool(csv_path is not None and csv_path.exists())
            fold_entries = _available_fold_csvs_for_experiment(exp_dir, method, subset)
            row[f'{method}_n_fold_csv'] = len(fold_entries)
        rows.append(row)
    pd.DataFrame(rows).to_csv(summary_path, index=False)
    print(f'[OK] Saved {summary_path}')
    return saved


def aggregate_one_dir(xai_plot_dir, subset, dpi, max_cols, overwrite):
    xai_plot_dir = Path(xai_plot_dir)
    split_dirs = _find_split_dirs(xai_plot_dir, subset)
    if not split_dirs:
        print(f'[WARN] No split_* projection dirs found in {xai_plot_dir} for subset={subset}')
        return []

    output_dir = xai_plot_dir / OUTPUT_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)

    saved = []
    chunks = _chunked(split_dirs, max_cols)
    multi_chunk = len(chunks) > 1

    for chunk_idx, chunk in enumerate(chunks, start=1):
        suffix = f'_part{chunk_idx:02d}' if multi_chunk else ''
        for method, method_label in METHODS:
            saved.extend(
                _save_method_panel(
                    xai_plot_dir=xai_plot_dir,
                    split_dirs=chunk,
                    method=method,
                    method_label=method_label,
                    subset=subset,
                    output_dir=output_dir,
                    dpi=dpi,
                    overwrite=overwrite,
                    suffix=suffix,
                )
            )
        saved.extend(
            _save_full_panel(
                xai_plot_dir=xai_plot_dir,
                split_dirs=chunk,
                subset=subset,
                output_dir=output_dir,
                dpi=dpi,
                overwrite=overwrite,
                suffix=suffix,
            )
        )

    summary_path = output_dir / f'per_fold_embedding_plot_summary_{subset}.csv'
    summary_rows = []
    for split_dir in split_dirs:
        row = {'split_dir': str(split_dir), 'fold': _display_fold_name(split_dir)}
        for method, _ in METHODS:
            row[f'{method}_csv'] = str(_method_csv_path(split_dir, method, subset))
            row[f'{method}_exists'] = _method_csv_path(split_dir, method, subset).exists()
        summary_rows.append(row)
    pd.DataFrame(summary_rows).to_csv(summary_path, index=False)
    print(f'[OK] Saved {summary_path}')
    return saved


def main():
    args = parse_args()

    total_saved = 0
    model_dirs = set()

    if args.xai_plot_dir:
        input_dir = Path(args.xai_plot_dir)
        if _is_model_dir(input_dir):
            xai_dirs = []
            model_dirs.add(input_dir)
            for exp_name in EXPERIMENT_ORDER:
                exp_dir = input_dir / exp_name
                if exp_dir.is_dir():
                    xai_dirs.append(exp_dir)
            for exp_dir in _find_experiment_dirs_for_model(input_dir):
                if exp_dir not in xai_dirs:
                    xai_dirs.append(exp_dir)
        else:
            xai_dirs = [input_dir]
            model_dirs.add(input_dir.parent)
    else:
        root = Path(args.root) if args.root else _default_root()
        xai_dirs = _find_candidate_dirs(root, args.model_filter)
        model_dirs.update({xai_dir.parent for xai_dir in xai_dirs})
        model_dirs.update(_find_model_dirs(root, args.model_filter))

    if not xai_dirs and not model_dirs:
        print('[WARN] No candidate XAI embedding plot directories found.')
        return

    if not args.skip_per_fold:
        print(f'Found {len(xai_dirs)} candidate fold-level XAI embedding plot directories.')
        for xai_dir in xai_dirs:
            print(f'\n==== Aggregating folds: {xai_dir} ====')
            saved = aggregate_one_dir(
                xai_plot_dir=xai_dir,
                subset=args.subset,
                dpi=args.dpi,
                max_cols=args.max_cols,
                overwrite=args.overwrite,
            )
            total_saved += len(saved)

    if not args.skip_across_splits:
        model_dirs = sorted(model_dirs)
        print(f'\nFound {len(model_dirs)} candidate model directories for across-split panels.')
        for model_dir in model_dirs:
            print(f'\n==== Aggregating split strategies: {model_dir} ====')
            saved = aggregate_across_splits_for_model(
                model_dir=model_dir,
                subset=args.subset,
                dpi=args.dpi,
                overwrite=args.overwrite,
                make_fold_grid=not args.skip_across_split_fold_grid,
            )
            total_saved += len(saved)

    print(f'\nDone. Saved or found {total_saved} aggregate panel file(s).')


if __name__ == '__main__':
    main()
